### ISSUE TITLE
startDbBootstrap dereferences a possibly-null harnessProxy, breaking typecheck for consuming apps

### ISSUE THREAD

**Issue by dt2patel** [hotwax/accxui#160]
## Summary

`startDbBootstrap()` in `common/db/sync/appDbBootstrap.ts` calls `harnessProxy.start(...)` without a null guard. `harnessProxy` is declared `Remote<SyncHarness> | null` and is only assigned inside `if (!workerInstance)`, so when a worker instance already exists but the proxy is `null`, line 43 dereferences null.

Every other use of `harnessProxy` in the file guards first (lines 61, 67, 81, 109, 142). Line 43 is the only unguarded one.

## Code

`common/db/sync/appDbBootstrap.ts`

```ts
let harnessProxy: Remote<SyncHarness> | null = null;   // L18

export async function startDbBootstrap(config: BootstrapConfig): Promise<void> {
  ...
    if (!workerInstance) {                              // L38
      workerInstance = config.workerFactory();
      harnessProxy = wrap<SyncHarness>(workerInstance); // L40 — only assigned here
    }

    await harnessProxy.start({                          // L43 — unguarded
      token: config.token,
      ...
    });
```

Introduced in 480b388 ("Improved: rename the cache vocabulary to db", 2026-09-04).

## Impact

This fails `vue-tsc`:

```
common/db/sync/appDbBootstrap.ts(43,11): error TS18047: 'harnessProxy' is possibly 'null'.
```

Consuming apps reach this file transitively through the `@common` barrel (`common/index.ts:71` → `export * from './db'` → `common/db/index.ts:15` → `export * from "./sync/appDbBootstrap"`), so it lands in their typecheck graph whether or not they use the API.

The effect differs by how each app defines its `build` script, since CI runs `pnpm --filter <app> build`:

- **`hotwax/order-routing`** — `build` is `pnpm typecheck && pnpm test:unit && vite build`, so CI fails at typecheck. `main` has been red since 0658cac (2026-09-04); last green run was ffdbfef (2026-08-18). Verbatim from the run log:
  ```
  ##[error]../../common/db/sync/appDbBootstrap.ts(43,11): error TS18047: 'harnessProxy' is possibly 'null'.
   ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  order-routing@2.2.0 build: `pnpm typecheck && pnpm test:unit && vite build`
  ```
  Every order-routing PR that merges current `main` inherits this red build.
- **`hotwax/company`** — `build` is just `vite build`, so the error is never surfaced in CI (esbuild strips types without checking). Running `pnpm typecheck` there does report it. Company does not call this API at runtime; it still uses its own local `src/services/appCacheBootstrap.ts`.

Tag-based release deploys are unaffected: `firebase-hosting-release.yml` pins `accxuiVersion: v1.5.0` (2026-08-14), which predates this file.

## Candidate fix

Widen the guard so the proxy is always assigned before use, which also closes the latent null-deref rather than just silencing the type error:

```ts
if (!workerInstance || !harnessProxy) {
  workerInstance = config.workerFactory();
  harnessProxy = wrap<SyncHarness>(workerInstance);
}
```

Not applied — filing for triage only.

## Reproduce

```bash
pnpm --filter order-routing typecheck
```
